version: "3.5"

services:

  web:
    image: nginx

    ports:
      - 80

    deploy:
      replicas: 2
      update_config:
        order: start-first

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2

      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 50M

    logging:
      options:
        max-size: "10m"
        max-file: "5"
